title:             Glimpse of The Past
email:             freddyxiong02@gmail.com
description:       Every Person Deserves Their History
author:            Frederic Xiong
#url:               "localhost:4000"
url:               "Fredericx172.github.io"
baseurl:           
=======
email:             Freddyxiong02@gmail.com
description:       Connect to the future, observe the past.
author:            Frederic Xiong
#url:               "localhost:4000"
url:               "http://fredericx172.github.io/"
baseurl:            "glimpseofthepast.org"


# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
